#!/usr/bin/env python3
from bootstrap.app import Protodown
from app.console.kernel import Kernel

app=Protodown()

if(vars(app.args)):                     # vars(args) != {}
    print(app.args.func(app.args))   #dispatch from thread
else:                               # vars(args) == {}
    app.print_help()
